// NY State Counties with estimated publication costs
// Publication costs vary by county based on local newspaper rates
export const NY_COUNTIES = [
  { name: "Albany", publishingCost: 200 },
  { name: "Allegany", publishingCost: 180 },
  { name: "Bronx", publishingCost: 1500 },
  { name: "Broome", publishingCost: 250 },
  { name: "Cattaraugus", publishingCost: 190 },
  { name: "Cayuga", publishingCost: 220 },
  { name: "Chautauqua", publishingCost: 210 },
  { name: "Chemung", publishingCost: 240 },
  { name: "Chenango", publishingCost: 190 },
  { name: "Clinton", publishingCost: 200 },
  { name: "Columbia", publishingCost: 300 },
  { name: "Cortland", publishingCost: 210 },
  { name: "Delaware", publishingCost: 200 },
  { name: "Dutchess", publishingCost: 450 },
  { name: "Erie", publishingCost: 350 },
  { name: "Essex", publishingCost: 190 },
  { name: "Franklin", publishingCost: 180 },
  { name: "Fulton", publishingCost: 190 },
  { name: "Genesee", publishingCost: 200 },
  { name: "Greene", publishingCost: 250 },
  { name: "Hamilton", publishingCost: 170 },
  { name: "Herkimer", publishingCost: 190 },
  { name: "Jefferson", publishingCost: 220 },
  { name: "Kings (Brooklyn)", publishingCost: 1400 },
  { name: "Lewis", publishingCost: 170 },
  { name: "Livingston", publishingCost: 200 },
  { name: "Madison", publishingCost: 210 },
  { name: "Monroe", publishingCost: 400 },
  { name: "Montgomery", publishingCost: 180 },
  { name: "Nassau", publishingCost: 900 },
  { name: "New York (Manhattan)", publishingCost: 1600 },
  { name: "Niagara", publishingCost: 280 },
  { name: "Oneida", publishingCost: 260 },
  { name: "Onondaga", publishingCost: 350 },
  { name: "Ontario", publishingCost: 220 },
  { name: "Orange", publishingCost: 500 },
  { name: "Orleans", publishingCost: 180 },
  { name: "Oswego", publishingCost: 210 },
  { name: "Otsego", publishingCost: 200 },
  { name: "Putnam", publishingCost: 450 },
  { name: "Queens", publishingCost: 1450 },
  { name: "Rensselaer", publishingCost: 250 },
  { name: "Richmond (Staten Island)", publishingCost: 1300 },
  { name: "Rockland", publishingCost: 750 },
  { name: "Saratoga", publishingCost: 280 },
  { name: "Schenectady", publishingCost: 240 },
  { name: "Schoharie", publishingCost: 170 },
  { name: "Schuyler", publishingCost: 160 },
  { name: "Seneca", publishingCost: 180 },
  { name: "St. Lawrence", publishingCost: 190 },
  { name: "Steuben", publishingCost: 200 },
  { name: "Suffolk", publishingCost: 850 },
  { name: "Sullivan", publishingCost: 230 },
  { name: "Tioga", publishingCost: 180 },
  { name: "Tompkins", publishingCost: 270 },
  { name: "Ulster", publishingCost: 320 },
  { name: "Warren", publishingCost: 220 },
  { name: "Washington", publishingCost: 190 },
  { name: "Wayne", publishingCost: 200 },
  { name: "Westchester", publishingCost: 1100 },
  { name: "Wyoming", publishingCost: 170 },
  { name: "Yates", publishingCost: 170 },
];

export function getCountyPublishingCost(countyName: string): number {
  const county = NY_COUNTIES.find((c) => c.name === countyName);
  return county?.publishingCost || 300; // Default if not found
}
